export const riskSummary = {
  expectedDelayDays: 19.2,
  delayedOrderCount: 18,
  materialShortageCount: 3,
  materialShortageQuantity: 5400,
  criticalOrderCount: 5,
  overallRiskLevel: 'HIGH',
};

export const riskItems = [
  {
    id: 1,
    orderNo: 'ORD-198',
    customerName: 'A사',
    productName: 'ABS-Black',
    productGroup: 'ABS',
    quantity: 1000,
    completedQuantity: 300,
    remainingQuantity: 700,
    dueDate: '2026-06-21',
    progressRate: 30,
    lineName: 'LINE-ABS-01',
    riskLevel: 'CRITICAL',
  },
  {
    id: 2,
    orderNo: 'ORD-199',
    customerName: 'B사',
    productName: 'PP-Heat',
    productGroup: 'PP',
    quantity: 800,
    completedQuantity: 400,
    remainingQuantity: 400,
    dueDate: '2026-08-18',
    progressRate: 50,
    lineName: 'LINE-PP-01',
    riskLevel: 'WARNING',
  },
  {
    id: 3,
    orderNo: 'ORD-200',
    customerName: 'C사',
    productName: 'PE-Clear',
    productGroup: 'PE',
    quantity: 600,
    completedQuantity: 372,
    remainingQuantity: 228,
    dueDate: '2026-09-06',
    progressRate: 62,
    lineName: 'LINE-PE-01',
    riskLevel: 'CAUTION',
  },
  {
    id: 4,
    orderNo: 'ORD-201',
    customerName: 'D사',
    productName: 'ABS-Gray',
    productGroup: 'ABS',
    quantity: 500,
    completedQuantity: 400,
    remainingQuantity: 100,
    dueDate: '2026-06-29',
    progressRate: 80,
    lineName: 'LINE-ABS-02',
    riskLevel: 'CAUTION',
  },
  {
    id: 5,
    orderNo: 'ORD-202',
    customerName: 'E사',
    productName: 'PP-Heat',
    productGroup: 'PP',
    quantity: 700,
    completedQuantity: 665,
    remainingQuantity: 35,
    dueDate: '2026-07-13',
    progressRate: 95,
    lineName: 'LINE-PP-02',
    riskLevel: 'SAFE',
  },
  {
    id: 6,
    orderNo: 'ORD-205',
    customerName: 'F사',
    productName: 'PA-Natural',
    productGroup: 'PA',
    quantity: 1200,
    completedQuantity: 528,
    remainingQuantity: 672,
    dueDate: '2026-07-04',
    progressRate: 44,
    lineName: 'LINE-PA-01',
    riskLevel: 'WARNING',
  },
];

export const riskDetailMap = {
  'ORD-198': {
    riskLevel: 'CRITICAL',
    riskLevelLabel: '매우 위험',
    delayProbability: 0.86,
    predictedAt: '2026-06-10 09:30',
    title: '리스크 상세 분석',
    causeTypes: ['MATERIAL_SHORTAGE', 'LOW_YIELD', 'LINE_WAITING_INCREASE'],
    summary: '분석 결과 ORD-198 주문건은 지연 위험이 매우 높은 상태입니다. 스케줄링 관리가 필요합니다.',
    progressMessage: '현재 주문 수량 1000개 중 300개가 완료되어 있으며, 700개가 진행 중 혹은 미완료 상태입니다.',
    recommendation:
      '해당 주문 건을 가속해서 생산하기 위해서는 LINE-ABS-01과 LINE-ABS-02에서 ORD-198 제품을 생산할 수 있도록 변경하는 것이 적절합니다. 두 라인의 평균 가동률이 90% 이상이어야 마감 기한 안에 모든 수량을 완료할 수 있습니다.',
    causes: [
      'ABS 제품군 주문 비중이 높아 LINE-ABS 계열 라인에 작업이 집중되어 있습니다.',
      '현재 완료 수량 대비 잔여 수량이 많아 납기일 내 생산 완료 가능성이 낮습니다.',
      'LINE-ABS-01 단일 라인 기준으로는 남은 수량을 처리하기 어렵습니다.',
    ],
  },

  'ORD-199': {
    riskLevel: 'WARNING',
    riskLevelLabel: '위험',
    delayProbability: 0.62,
    predictedAt: '2026-06-10 09:35',
    title: '리스크 상세 분석',
    causeTypes: ['LINE_WAITING_INCREASE', 'LOW_THROUGHPUT'],
    summary: 'ORD-199 주문건은 지연 위험이 있는 상태입니다. PP 제품군 라인 부하를 확인해야 합니다.',
    progressMessage: '현재 주문 수량 800개 중 400개가 완료되어 있으며, 400개가 남아 있습니다.',
    recommendation: 'LINE-PP-01의 작업량이 증가하고 있으므로 LINE-PP-02로 일부 물량을 분산하는 방안을 검토하세요.',
    causes: ['PP 제품군 주문 비중이 가장 높아 LINE-PP 라인의 부하가 큽니다.', '현재 생산 속도 기준으로 납기 여유가 충분하지 않습니다.'],
  },

  'ORD-200': {
    riskLevel: 'CAUTION',
    riskLevelLabel: '주의',
    delayProbability: 0.35,
    predictedAt: '2026-06-10 09:40',
    title: '리스크 상세 분석',
    causeTypes: ['LOW_THROUGHPUT'],
    summary: 'ORD-200 주문건은 현재 주의 단계입니다. PE 제품군 생산 진행률과 라인 여유 시간을 확인해야 합니다.',
    progressMessage: '현재 주문 수량 600개 중 372개가 완료되어 있으며, 228개가 남아 있습니다.',
    recommendation: '현재 계획을 유지하되 LINE-PE-01의 작업 지연 여부를 지속적으로 모니터링하세요.',
    causes: [
      '잔여 수량은 크지 않지만 납기 여유 시간이 충분하지 않습니다.',
      'PE 제품군 라인에 후속 주문이 예정되어 있어 일정 지연 시 영향이 확대될 수 있습니다.',
    ],
  },

  'ORD-201': {
    riskLevel: 'CAUTION',
    riskLevelLabel: '주의',
    delayProbability: 0.28,
    predictedAt: '2026-06-10 09:45',
    title: '리스크 상세 분석',
    causeTypes: ['LINE_WAITING_INCREASE', 'MACHINE_STATUS_ABNORMAL'],
    summary: 'ORD-201 주문건은 주의 단계입니다. ABS 제품군 라인 부하에 따라 지연 가능성이 발생할 수 있습니다.',
    progressMessage: '현재 주문 수량 500개 중 400개가 완료되어 있으며, 100개가 남아 있습니다.',
    recommendation: 'LINE-ABS-02의 현재 작업 종료 시점을 확인하고, 필요 시 후속 작업 순서를 조정하세요.',
    causes: [
      'ABS 제품군 주문이 LINE-ABS 계열에 집중되어 있습니다.',
      '잔여 수량은 적지만 선행 작업 지연 시 납기 위험이 증가할 수 있습니다.',
    ],
  },

  'ORD-202': {
    riskLevel: 'SAFE',
    riskLevelLabel: '안전',
    delayProbability: 0.08,
    predictedAt: '2026-06-10 09:50',
    title: '리스크 상세 분석',
    causeTypes: [],
    summary: 'ORD-202 주문건은 현재 안전 단계입니다. 현재 생산계획 기준 납기 내 완료 가능성이 높습니다.',
    progressMessage: '현재 주문 수량 700개 중 665개가 완료되어 있으며, 35개가 남아 있습니다.',
    recommendation: '현재 계획을 유지해도 무리가 없으며, 별도 생산계획 조정은 필요하지 않습니다.',
    causes: ['진행률이 높고 잔여 생산량이 적습니다.', '현재 배정된 LINE-PP-02 기준 납기 내 완료 가능성이 높습니다.'],
  },

  'ORD-205': {
    riskLevel: 'WARNING',
    riskLevelLabel: '위험',
    delayProbability: 0.68,
    predictedAt: '2026-06-10 09:55',
    title: '리스크 상세 분석',
    causeTypes: ['MATERIAL_SHORTAGE', 'LINE_WAITING_INCREASE'],
    summary:
      'ORD-205 주문건은 자재 부족으로 인해 계획된 생산 투입 시점이 지연될 가능성이 있습니다. PA-Natural 원료 입고 일정과 라인 대기 작업을 함께 확인해야 합니다.',
    progressMessage: '현재 주문 수량 1200개 중 528개가 완료되어 있으며, 672개가 남아 있습니다.',
    recommendation:
      'PA-Natural 원료 입고 일정을 확인하고, 필요 시 대체 자재 사용 또는 생산 가능 라인으로 일부 물량을 분산하는 방안을 검토하세요.',
    causes: [
      'PA-Natural 생산에 필요한 주요 원료의 입고 수량이 계획 대비 부족합니다.',
      '선행 작업과 전환 작업이 겹쳐 주문 투입이 늦어질 수 있습니다.',
    ],
  },
};
