export const lineStatusMeta = {
  RUNNING: { label: "가동 중", tone: "normal" },
  IDLE: { label: "대기", tone: "pending" },
  SETUP: { label: "전환/준비 중", tone: "risk" },
  STOPPED: { label: "정지", tone: "cancelled" },
  ERROR: { label: "오류", tone: "shortage" },
  MAINTENANCE: { label: "점검", tone: "risk" },
  WAITING: { label: "대기", tone: "pending" },
  SCHEDULED: { label: "예정", tone: "pending" },
  IN_PROGRESS: { label: "진행 중", tone: "normal" },
  COMPLETED: { label: "완료", tone: "normal" },
  DELAYED: { label: "지연", tone: "shortage" },
  CANCELLED: { label: "취소", tone: "cancelled" },
};

export const lineStatusOptions = [
  { value: "all", label: "전체 상태" },
  { value: "RUNNING", label: "가동 중" },
  { value: "IDLE", label: "대기" },
  { value: "SETUP", label: "전환/준비 중" },
  { value: "STOPPED", label: "정지" },
  { value: "ERROR", label: "오류" },
  { value: "MAINTENANCE", label: "점검" },
];

export const pageSizeOptions = [
  { value: "5", label: "5개" },
  { value: "10", label: "10개" },
  { value: "15", label: "15개" },
];

export const lineItems = [
  {
    id: "LINE-A",
    name: "Line A",
    utilizationRate: 80,
    currentProduct: "ABS-Black",
    nextProduct: "ABS-White",
    nextChangeEta: "1.2h 후",
    status: "RUNNING",
    equipments: [
      { name: "압출기 01", label: "압출01", status: "running" },
      { name: "혼합기 01", label: "혼합01", status: "running" },
      { name: "냉각기 01", label: "냉각01", status: "running" },
      { name: "검사기 01", label: "검사01", status: "idle" },
      { name: "포장기 01", label: "포장01", status: "maintenance" },
    ],
  },
  {
    id: "LINE-B",
    name: "Line B",
    utilizationRate: 55,
    currentProduct: "PP-Heat",
    nextProduct: "PP-Clear",
    nextChangeEta: "1.5h 후",
    status: "RUNNING",
    equipments: [
      { name: "압출기 02", label: "압출02", status: "running" },
      { name: "배합기 01", label: "배합01", status: "running" },
      { name: "냉각기 02", label: "냉각02", status: "stopped" },
      { name: "검사기 02", label: "검사02", status: "error" },
      { name: "포장기 02", label: "포장02", status: "maintenance" },
    ],
  },
  {
    id: "LINE-C",
    name: "Line C",
    utilizationRate: 60,
    currentProduct: "PP-Heat",
    nextProduct: "PP-Heat",
    nextChangeEta: "0.5h 후",
    status: "RUNNING",
    equipments: [
      { name: "혼합기 01", label: "혼합01", status: "running" },
      { name: "배합기 02", label: "배합02", status: "running" },
      { name: "검사기 03", label: "검사03", status: "idle" },
      { name: "냉각기 03", label: "냉각03", status: "stopped" },
      { name: "포장기 03", label: "포장03", status: "error" },
    ],
  },
  {
    id: "LINE-D",
    name: "Line D",
    utilizationRate: 36,
    currentProduct: "Additive-X",
    nextProduct: "PP-Clear",
    nextChangeEta: "1.0h 후",
    status: "MAINTENANCE",
    equipments: [
      { name: "배합기 03", label: "배합03", status: "running" },
      { name: "압출기 03", label: "압출03", status: "idle" },
      { name: "냉각기 04", label: "냉각04", status: "stopped" },
      { name: "검사기 04", label: "검사04", status: "error" },
      { name: "포장기 04", label: "포장04", status: "maintenance" },
    ],
  },
  {
    id: "LINE-E",
    name: "Line E",
    utilizationRate: 0,
    currentProduct: "Colorant-B",
    nextProduct: "ABS-Black",
    nextChangeEta: "24h 후",
    status: "WAITING",
    equipments: [
      { name: "압출기 05", label: "압출05", status: "idle" },
      { name: "혼합기 02", label: "혼합02", status: "stopped" },
      { name: "배합기 04", label: "배합04", status: "stopped" },
      { name: "검사기 05", label: "검사05", status: "error" },
      { name: "포장기 05", label: "포장05", status: "maintenance" },
    ],
  },
  {
    id: "LINE-F",
    name: "Line F",
    utilizationRate: 15,
    currentProduct: "ABS-Gray",
    nextProduct: "ABS-Purple",
    nextChangeEta: "3.0h 후",
    status: "STOPPED",
    equipments: [
      { name: "압출기 04", label: "압출04", status: "running" },
      { name: "혼합기 03", label: "혼합03", status: "idle" },
      { name: "냉각기 05", label: "냉각05", status: "stopped" },
      { name: "검사기 06", label: "검사06", status: "error" },
      { name: "포장기 06", label: "포장06", status: "maintenance" },
    ],
  },
];

export const productionOrders = [
  {
    id: "PO-240520-001",
    product: "ABS-Black",
    orderAmountKg: 10000,
    lineCount: 3,
    totalProducedKg: 5500,
    progressRate: 55,
    daysUntilDeadline: 20,
    lineDetails: [
      {
        lineName: "Line A",
        productName: "ABS-Black",
        plannedKg: 4000,
        producedKg: 2200,
        progressRate: 55,
        status: "RUNNING",
        changeEta: "1.2h 후",
      },
      {
        lineName: "Line C",
        productName: "ABS-Black",
        plannedKg: 3000,
        producedKg: 1800,
        progressRate: 60,
        status: "RUNNING",
        changeEta: "0.5h 후",
      },
      {
        lineName: "Line E",
        productName: "ABS-Black",
        plannedKg: 3000,
        producedKg: 1500,
        progressRate: 50,
        status: "WAITING",
        changeEta: "24h 후",
      },
    ],
  },
  {
    id: "PO-240521-014",
    product: "PP-Heat",
    orderAmountKg: 8200,
    lineCount: 2,
    totalProducedKg: 4710,
    progressRate: 57,
    daysUntilDeadline: 12,
    lineDetails: [
      {
        lineName: "Line B",
        productName: "PP-Heat",
        plannedKg: 4200,
        producedKg: 2410,
        progressRate: 57,
        status: "RUNNING",
        changeEta: "1.5h 후",
      },
      {
        lineName: "Line C",
        productName: "PP-Heat",
        plannedKg: 4000,
        producedKg: 2300,
        progressRate: 58,
        status: "RUNNING",
        changeEta: "0.5h 후",
      },
    ],
  },
  {
    id: "PO-240525-006",
    product: "Additive-X",
    orderAmountKg: 3600,
    lineCount: 1,
    totalProducedKg: 1296,
    progressRate: 36,
    daysUntilDeadline: 7,
    lineDetails: [
      {
        lineName: "Line D",
        productName: "Additive-X",
        plannedKg: 3600,
        producedKg: 1296,
        progressRate: 36,
        status: "MAINTENANCE",
        changeEta: "1.0h 후",
      },
    ],
  },
];
