export const initialOrders = [
  {
    id: "PO-240520-001",
    customer: "A사",
    product: "ABS-Black",
    quantity: 1000,
    dueDate: "2026-06-21",
    status: "IN_PROGRESS",
    productionStartDate: "2026-05-28",
    productionManager: "윤정원",
    customerManager: "배난수",
    priority: 1,
    expectedLeadDays: 24,
  },
  {
    id: "PO-240520-002",
    customer: "B사",
    product: "PP-Heat",
    quantity: 800,
    dueDate: "2026-08-18",
    status: "DELAYED",
    productionStartDate: "2026-07-30",
    productionManager: "박시우",
    customerManager: "한도윤",
    priority: 1,
    expectedLeadDays: 19,
  },
  {
    id: "PO-240520-003",
    customer: "C사",
    product: "PE-Clear",
    quantity: 600,
    dueDate: "2026-09-06",
    status: "IN_PROGRESS",
    productionStartDate: "2026-08-12",
    productionManager: "정유나",
    customerManager: "이유림",
    priority: 2,
    expectedLeadDays: 16,
  },
  {
    id: "PO-240520-004",
    customer: "D사",
    product: "ABS-Gray",
    quantity: 500,
    dueDate: "2026-06-29",
    status: "IN_PROGRESS",
    productionStartDate: "2026-06-02",
    productionManager: "김우진",
    customerManager: "최민아",
    priority: 2,
    expectedLeadDays: 18,
  },
  {
    id: "PO-240520-005",
    customer: "E사",
    product: "PP-Heat",
    quantity: 700,
    dueDate: "2026-07-13",
    status: "DELAYED",
    productionStartDate: "2026-06-26",
    productionManager: "신지훈",
    customerManager: "권아인",
    priority: 1,
    expectedLeadDays: 21,
  },
  {
    id: "PO-240520-006",
    customer: "F사",
    product: "PE-Clear",
    quantity: 900,
    dueDate: "2026-07-30",
    status: "WAITING",
    productionStartDate: "2026-07-10",
    productionManager: "이서준",
    customerManager: "장하나",
    priority: 3,
    expectedLeadDays: 20,
  },
  {
    id: "PO-240520-007",
    customer: "G사",
    product: "ABS-Black",
    quantity: 1200,
    dueDate: "2026-08-05",
    status: "WAITING",
    productionStartDate: "2026-07-17",
    productionManager: "강도현",
    customerManager: "나유정",
    priority: 2,
    expectedLeadDays: 27,
  },
  {
    id: "PO-240520-008",
    customer: "H사",
    product: "PP-Heat",
    quantity: 1000,
    dueDate: "2026-08-12",
    status: "WAITING",
    productionStartDate: "2026-07-22",
    productionManager: "유민석",
    customerManager: "오지수",
    priority: 3,
    expectedLeadDays: 22,
  },
];

export const statusMeta = {
  WAITING: { label: "예정", tone: "pending" },
  IN_PROGRESS: { label: "진행 중", tone: "normal" },
  COMPLETED: { label: "완료", tone: "normal" },
  DELAYED: { label: "지연", tone: "shortage" },
  CANCELLED: { label: "취소", tone: "cancelled" },
  PLANNED: { label: "예정", tone: "pending" },
};

export const statusOptions = [
  { value: "all", label: "상태 전체" },
  { value: "WAITING", label: "예정" },
  { value: "IN_PROGRESS", label: "진행 중" },
  { value: "COMPLETED", label: "완료" },
  { value: "DELAYED", label: "지연" },
  { value: "CANCELLED", label: "취소" },
];

export const pageSizeOptions = [
  { value: "10", label: "10건" },
  { value: "20", label: "20건" },
  { value: "50", label: "50건" },
];
