export const statusOptions = [
  { value: "all", label: "전체 자재" },
  { value: "normal", label: "정상" },
  { value: "risk", label: "부족위험" },
  { value: "shortage", label: "부족" },
  { value: "pending", label: "입고대기" },
];

export const pageSizeOptions = [
  { value: "10", label: "10건" },
  { value: "20", label: "20건" },
  { value: "30", label: "30건" },
];

export const statusMeta = {
  normal: { label: "정상", tone: "normal" },
  risk: { label: "부족위험", tone: "risk" },
  shortage: { label: "부족", tone: "shortage" },
  pending: { label: "입고대기", tone: "pending" },
};

export const inventoryCardIds = [
  "Re-001",
  "Re-002",
  "Re-003",
  "Ad-x",
  "Co-b",
  "Co-a",
  "St-011",
  "Pa-020",
  "Mb-101",
  "Sl-008",
  "Cl-210",
  "Lb-404",
  "Re-004",
  "Pe-014",
  "Co-c",
  "Ad-y",
  "Fi-101",
  "Re-005",
];

export const materialCatalog = [
  { id: "Re-001", name: "ABS Resin", product: "ABS-Black" },
  { id: "Re-002", name: "PP Resin", product: "PP-Heat" },
  { id: "Re-003", name: "PE Resin", product: "PP-Heat, PE-Clear" },
  { id: "Ad-x", name: "Additive-X", product: "PP-Heat" },
  { id: "Co-b", name: "Colorant-B", product: "ABS-Black, PP-Heat" },
  { id: "Co-a", name: "Colorant-A", product: "ABS-Black, PP-Heat" },
  { id: "St-011", name: "Stabilizer-11", product: "PE-Clear" },
  { id: "Pa-020", name: "Packaging Film", product: "전 제품군" },
  { id: "Mb-101", name: "Masterbatch-101", product: "ABS-White" },
  { id: "Sl-008", name: "Solvent-08", product: "코팅 공정" },
];

export const mockServerMaterialDefaults = {
  depletionDate: "26/08/14",
  safeStock: 3000,
  levelLabel: "68%",
  status: "pending",
};

export const initialMaterials = [
  {
    id: "Re-001",
    name: "ABS Resin",
    product: "ABS-Black",
    depletionDate: "26/07/18",
    currentStock: 2300,
    safeStock: 3000,
    levelLabel: "78%",
    status: "normal",
  },
  {
    id: "Re-002",
    name: "PP Resin",
    product: "PP-Heat",
    depletionDate: "26/07/18",
    currentStock: 1860,
    safeStock: 3000,
    levelLabel: "62%",
    status: "risk",
  },
  {
    id: "Re-003",
    name: "PE Resin",
    product: "PP-Heat, PE-Clear",
    depletionDate: "26/07/18",
    currentStock: 900,
    safeStock: 2000,
    levelLabel: "45%",
    status: "risk",
  },
  {
    id: "Ad-x",
    name: "Additive-X",
    product: "PP-Heat",
    depletionDate: "26/07/18",
    currentStock: 480,
    safeStock: 1500,
    levelLabel: "32%",
    status: "shortage",
  },
  {
    id: "Co-b",
    name: "Colorant-B",
    product: "ABS-Black, PP-Heat",
    depletionDate: "26/07/18",
    currentStock: 2430,
    safeStock: 3000,
    levelLabel: "81%",
    status: "normal",
  },
  {
    id: "Co-a",
    name: "Colorant-A",
    product: "ABS-Black, PP-Heat",
    depletionDate: "26/07/18",
    currentStock: 2100,
    safeStock: 3000,
    levelLabel: "70%",
    status: "normal",
  },
  {
    id: "St-011",
    name: "Stabilizer-11",
    product: "PE-Clear",
    depletionDate: "26/07/20",
    currentStock: 1510,
    safeStock: 2000,
    levelLabel: "76%",
    status: "pending",
  },
  {
    id: "Pa-020",
    name: "Packaging Film",
    product: "전 제품군",
    depletionDate: "26/07/19",
    currentStock: 5400,
    safeStock: 6000,
    levelLabel: "90%",
    status: "normal",
  },
  {
    id: "Mb-101",
    name: "Masterbatch-101",
    product: "ABS-White",
    depletionDate: "26/07/22",
    currentStock: 3400,
    safeStock: 3200,
    levelLabel: "106%",
    status: "normal",
  },
  {
    id: "Sl-008",
    name: "Solvent-08",
    product: "코팅 공정",
    depletionDate: "26/07/21",
    currentStock: 690,
    safeStock: 1600,
    levelLabel: "43%",
    status: "shortage",
  },
  {
    id: "Cl-210",
    name: "Cleaner-210",
    product: "Line B, C",
    depletionDate: "26/07/25",
    currentStock: 1250,
    safeStock: 1800,
    levelLabel: "69%",
    status: "risk",
  },
  {
    id: "Lb-404",
    name: "Lubricant-404",
    product: "압출 공정",
    depletionDate: "26/07/23",
    currentStock: 1880,
    safeStock: 1700,
    levelLabel: "111%",
    status: "normal",
  },
  {
    id: "Re-004",
    name: "ABS Resin-2",
    product: "ABS-Gray",
    depletionDate: "26/07/24",
    currentStock: 1720,
    safeStock: 3000,
    levelLabel: "57%",
    status: "risk",
  },
  {
    id: "Pe-014",
    name: "PE Resin-2",
    product: "PE-Matte",
    depletionDate: "26/07/28",
    currentStock: 760,
    safeStock: 1900,
    levelLabel: "40%",
    status: "shortage",
  },
  {
    id: "Co-c",
    name: "Colorant-C",
    product: "ABS-White, PP-Heat",
    depletionDate: "26/07/29",
    currentStock: 2250,
    safeStock: 3000,
    levelLabel: "75%",
    status: "normal",
  },
  {
    id: "Ad-y",
    name: "Additive-Y",
    product: "PE-Clear",
    depletionDate: "26/07/30",
    currentStock: 820,
    safeStock: 1500,
    levelLabel: "55%",
    status: "pending",
  },
  {
    id: "Fi-101",
    name: "Film-101",
    product: "포장 라인",
    depletionDate: "26/08/01",
    currentStock: 2800,
    safeStock: 3500,
    levelLabel: "80%",
    status: "normal",
  },
  {
    id: "Re-005",
    name: "PP Resin-2",
    product: "PP-Standard",
    depletionDate: "26/08/03",
    currentStock: 980,
    safeStock: 3000,
    levelLabel: "33%",
    status: "shortage",
  },
];
